[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    version = "5.11.1"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
